### ISSUE TITLE
Can't change Firefox preferences by serenity.properties

### ISSUE THREAD

**Issue by vivregenek** [serenity-bdd/serenity-core#1009]
serenity-core 1.6.0, selenium-java 3.5.3, geckodriver 0.19.0 FF 56.0.2 (64)

I am trying changed FF preferences with serenity.properties:
`firefox.preferences="browser.download.dir=C:\\temp;browser.helperApps.alwaysAsk.force=false;browser.download.manager.showWhenStarting=false;browser.download.useDownloadDir=true;browser.download.folderList=2;"`

But it doesn't work. In about:config I see deafult values for this preferences.  
Also get this entries in output

`INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
Separator = ;
arg = browser.download.dir=C:\temp\
arg = browser.helperApps.alwaysAsk.force=false
arg = browser.download.manager.showWhenStarting=false
arg = browser.download.useDownloadDir=true
arg = browser.download.folderList=2
arg = browser.helperApps.neverAsk.saveToDisk=text/html`

**Comment by wakaleo** [comment]
I suspect this is a gecko issue. See if it works in raw WebDriver, and drill into the FirefoxProfileEnhancer class to make sure the values you think are being applied to the Firefox profile object. If you can see that they are not being applied correctly, it would be a Serenity issue. If they are, you can close this issue and raise one with the Gecko team (see https://github.com/mozilla/geckodriver/issues)

**Comment by mmanach** [comment]
@vivregenek hello, maybe you can have a look at this one https://github.com/serenity-bdd/serenity-core/issues/935

Have some issues too for setting log level with ```firefox.preferences```

**Comment by wakaleo** [comment]
The latest versions of Selenium use the FirefoxOptions object instead of the Capabilities objects used by all the other drivers (but which are deprecated for Firefox). A good pull request for someone interested in contributing would be to refactor the FirefoxDriverProvider class (https://github.com/serenity-bdd/serenity-core/blob/158fb16c9029d2b6304a321726c40fbaa1fe4d4d/serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/FirefoxDriverProvider.java) to use FirefoxOptions instead of the Capabilities object.

**Comment by wakaleo** [comment]
(That said, I do not think the FirefoxOptions change is related to the issue you describe.

**Comment by vivregenek** [comment]
@wakaleo Thank you for answer! What you mean about raw WebDriver? Older vrsion with not use geckodriver (if yes wich versions driver and serenity, selenium I need use)? Also I tryied change preferences like this, and it's work (maybe it usefull information for you). But I want use serenity.propersties.
`FirefoxProfile profile = new FirefoxProfile();
        profile.setAcceptUntrustedCertificates(false);
        profile.setAssumeUntrustedCertificateIssuer(true);
        profile.setPreference("browser.download.folderList", 2);
        WebDriver driver = new FirefoxDriver(profile);`

**Comment by wakaleo** [comment]
The FirefoxDriverProvider and FirefoxProfileEnhancer classes should be doing essentially the same thing. Your fastest option would be to try debugging these classes and see what is going on when you use your property configuration. If you find something, propose a Pull Request and I will take a look. Otherwise it will have to wait until I get time to take a closer look.

**Comment by hariharanravichandran** [comment]
@vivregenek The below preferences seems to be working for me. Can you please try your firefox. preferences without ". firefox.preferences=browser.download.folderList=1;browser.download.manager.showWhenStarting=false;browser.helperApps.neverAsk.saveToDisk=application/csv

**Comment by nikitaratkevich** [comment]
@hariharanravichandran 
Thanks for your comment. It helped me to turn off geolocation for firefox:
firefox.preferences=geo.enabled=false
