### ISSUE TITLE
What is the bestWay to write a Stroy in Jbehave

### ISSUE THREAD

**Issue by siva90144** [serenity-bdd/serenity-core#1021]
Story-1

Given set the employee search request data
When request is executed
Then verify the response
Examples:
|empID|Age|City|JoiningYear|department|

Story-2

Given set the employee details to request
And set the department details
When request is executed
Then verify the response
Examples:
|empID|Age|City|JoiningYear|department|

what is the best way to write the stories? 

Do we need to write in-detail steps?

is it best way to include multiple AND statements in given, when  and then? or do we need to write in generic way?

**Comment by wakaleo** [comment]
This is a question on Gherkin style, rather than a Serenity bug, so StackOverflow would be a better channel. Neither of these is really written the way BDD scenarios are intended to be written. BDD scenarios are living documentation, so much more declarative than imperative, so expressions like "set the employee search request data" and "verify the response" read very oddly. A more BDD-style employeee
 search scenario might be something like:

```
Feature: Search for employees

Scenario: Search by name
Given the following employees:
Employee Number | First Name | Last Name | 
101                              | Paul              | Smith           | 
102.                            | Bill                | Paul              |
103                             | Bill                | Smith           |
When Sarah searches for an employee named Paul
Then Sarah should find the following employees:
Employee Number | First Name | Last Name | 
101                              | Paul              | Smith           | 
102.                            | Bill                | Paul               |
```

You can more find information about how to write good quality scenarios in [BDD in Action](https://www.amazon.com/BDD-Action-Behavior-driven-development-lifecycle/dp/161729165X/ref=sr_1_1?ie=UTF8&qid=1510430385&sr=8-1&keywords=bdd+in+action), or (if you prefer online courses) at the [Serenity Dojo](https://serenitydojo.teachable.com/p/bdd-with-cucumber-and-serenity).
