### ISSUE TITLE
StepListener's testRunFinished method is not invoked

### ISSUE THREAD

**Issue by Invictum** [serenity-bdd/serenity-core#1056]
Hi,
Serenity-core and serenity-junit version is 1.8.2
I am using `StepListening` for some integration and looking for method that indicates all tests set is executed and report generating is started.
Looks like `testRunFinished` should do what I need, but it is not invoked at all - at least in jUnit style tests. It looks like an issue.

**Comment by wakaleo** [comment]
You would think so. In JUnit it is called by the testRunFinished() method of the JUnitStepListener class (which implements RunListener). But it seems, JUnit never triggers this event (or I couldn't make it do so); this seems to be a JUnit issue.

Regarding "all the tests are finished", the problem is, we never really know that. Which is why the report generation is done in a separate phase.

**Comment by Invictum** [comment]
Thx for quick response. I will try to find another way.
