### ISSUE TITLE
Unable to set/override serenity property in test

### ISSUE THREAD

**Issue by SergheiRidico** [serenity-bdd/serenity-core#1183]
We have popup that appears every time in our application after the first launch.
All our tests are independent therefore every one starts from clean application installation.
Developers set for us process argument: 
`appium.processArguments = {"args": ["--show-popup", "false"]}`
and now we can skip popup, setting it's value in _serenity.properties_ file.
But we have several tests that require this popup. 

I decided to set property straight before specific test execution:
`SystemEnvironmentVariables.createEnvironmentVariables()
.setProperty("appium.processArguments", "{\"args\": [\"--show-popup\", \"true\"]}");`
But property hasn't changed.
When I tried to print property's value:
`System.out.println(SystemEnvironmentVariables.createEnvironmentVariables()
.getProperty("appium.processArguments"));`
I got value from _serenity.properties_ file, but the value that I set before the test.

- Serenity version: _1.9.3_
- Appium version: _1.7.2_
- iOS version: _11.2.6_

**Comment by wakaleo** [comment]
The system properties are read-only and loaded at the start of the test, it is unwise to change them during test execution. (And the code you show would have no effect in any case, as you are just creating a new set of environment variables unrelated to the ones used by the tests). If you want to do something special for a specific test, you will probably need to use a custom driver.

If this is a question rather than a defect report (which is what it appears to be), could you close the issue here and post the question on https://serenity-bdd.rocket.chat?

**Comment by SergheiRidico** [comment]
Thanks for your answer
