### ISSUE TITLE
Hybrid App automation using serenity

### ISSUE THREAD

**Issue by gsumit1** [serenity-bdd/serenity-core#1227]
To switch WEBVIEW for hybrid app,  we are using below code.

	public AndroidDriver<WebElement> androidDriverWeb() {
		AndroidDriver<WebElement> androidDriver = ((AndroidDriver<WebElement>) ((WebDriverFacade) 
		getDriver()).getProxiedDriver());
		Set<String> contextNames = androidDriver.getContextHandles();
		for (String contextName : contextNames) {
			if (contextName.contains("WEBVIEW")) {
				androidDriver.context(contextName);
				return androidDriver;
			}
		}
}
If we use above code, then at Page, we can't use @FindBy to identify webview WebElement. 
Then we are forced to use
androidDriverWeb().findElement(By.xxx("xxxxx")) to identify web element. 
All the in build wrapper methods develop around WebElementFacade make no sense for webElement.

My question is there any better way for this implementation, which will dynamically set the web context and we can use @FindBy to identify hybrid web element.

**Comment by cliviu** [comment]
hi @gsumit1 , you can check this example if you want https://github.com/cliviu/serenity-appium-hybrid-poc

**Comment by jitin03** [comment]
Any update on this, when we will have fix

**Comment by wakaleo** [comment]
@jitin03 Not sure what fix you refer to; did you look at Liviu's example?

**Comment by jitin03** [comment]
Hi,

Yes I have referred still getting exception(timeout for the given locator as I'd) while identifying element inside webview at iOS platform.

**Comment by wakaleo** [comment]
Sounds like a usage problem - have you asked on https://serenity-bdd.rocket.chat?

**Comment by jitin03** [comment]
Thanks, joined the room.

**Comment by dbirch-cognitoiq** [comment]
Seems to me like you're creating a new WebDriver instance, and changing the context of that, rather than grabbing the one that is created by Serenity and doing the context change in there.

We use code called from an @Before annotated setup method (cucumber, but whatever test runner will have a similar annotation to run before your test) something like:

```
AndroidDriver androidDriver = (AndroidDriver) ((WebDriverFacade) getDriver()).getProxiedDriver();
if (!androidDriver.getContext().equals(contextName)) {
	androidDriver.context(contextName);
}
```

Then just use @FindBy as usual in our page objects, similar to:
```
@FindBy(id = "elementId")
privateWebElementFacade elementToTest;
```

My suspicion is that somehow the generic typing of the android driver is causing an issue for you here.

Any reason you want to use WebElement rather than WebElementFacade? It seems with serenity the latter is pretty much always a better option.
