### ISSUE TITLE
Issue in implicitWait() .

### ISSUE THREAD

**Issue by JeffGaly** [serenity-bdd/serenity-core#1276]
I wish to make my page to wait for 3 minutes which will do a process of generating reports about 2 to 3 minutes.
I tried using implicitlyWait(),ExplicitWait() ,scriptwait(),pageloadtimeout ()but nothing works as page gets loaded to next step without waiting for 3 minutes.

Note :I dont wish to use thread.sleep() .
Any suggestions will be useful .

**Comment by wakaleo** [comment]
This is a question rather than a defect, so more appropriate for https://serenity-bdd.rocket.chat.

You are right not to use Thread.sleep(). The trick is to find something to wait for - the appearance of an element or the disappearance of an overlay, for example, or a particular database state. Then you could do something like this:

```
        waitForWithRefresh()
                .withTimeout(5, MINUTES)
                .until(driver -> driver.findElement(By.cssSelector("#login")));
```

**Comment by wakaleo** [comment]
More a question than a defect; could you post this on https://serenity-bdd.rocket.chat for a broader audience?

**Comment by JeffGaly** [comment]
thanks a lot @wakaleo .I used invisibilityof an element .
 wait.until(ExpectedConditions.invisibilityOf(element));
