### ISSUE TITLE
Want to set Identity user name as 'created by' 

### ISSUE THREAD

**Issue by afhossain** [serenity-bdd/serenity-core#1331]
I want to set 'CreatedBy' field with Identity(logged in ) user name . Please help with the code.

**Comment by wakaleo** [comment]
This is a question, rather than a defect, could you post it on https://serenity-bdd.rocket.chat to see if any of the Serenity community members might be able to help. Alternatively, you can ask for more tailored support with one of our commercial support package (see http://johnfergusonsmart.com/serenity-bdd-mentoring#support).
