### ISSUE TITLE
Create Tree View Structure in Serenity mvc

### ISSUE THREAD

**Issue by nareshIntelegain** [serenity-bdd/serenity-core#1351]
I want to  create 3 level tree view structure in serenity where user can edit details not only view please send me example code demo .Please send me asap.

Thanks in Advance,
Naresh

**Comment by wakaleo** [comment]
Hi Naresh,

We’d certainly be happy to help you out with your Serenity project. As this is a support request for your project, including some custom work, rather than a defect, please take a look at our enterprise support packages to decide the best way we can help.  

You can choose the support package that best suits your needs here: https://johnfergusonsmart.com/serenity-bdd-mentoring#support
