### ISSUE TITLE
Create serenity-bdd API

### ISSUE THREAD

**Issue by verhagen** [serenity-bdd/serenity-core#138]
**why:** Making it easier for new users the start with serenity-bdd

For new users all the packages can be quite overwhelming. What are the most imported interface and classes? What to use / extend etc. Which ones are relevant and which ones are less or not relevant.

My suggestion is to create a separate API library like `serenity-api.jar`. Users of serenity-bdd can just include the `serenity-api.jar` as _compile_ time dependency. And will only need the `serenity-core.jar` dependency during runtime _runtime_.

This would make it easier for user of the serenity-bdd library, as the api would just contain the important stuff they need, and the rest, all the machinery, to make it work, would be hidden away in the core library.

**Comment by RobWin** [comment]
+1

**Comment by wakaleo** [comment]
It's not quite as simple as that - the new classes generally extend the "classic" ones, and the "classic" ones that remain in general use (e.g. annotations) are there because changing them would result in massive breaking changes and a lot of rework for existing tests. But I will think about what can be done.
