### ISSUE TITLE
Serenity vulnerabilities

### ISSUE THREAD

**Issue by venumadhavancha** [serenity-bdd/serenity-core#1441]
[dependency-check-report.html.zip](https://github.com/serenity-bdd/serenity-core/files/2543433/dependency-check-report.html.zip)

)

Hi,
In our projects, we are using the following serenity libraries, it works awesome. But when we run the owasp dependency checker to check the vulnerabilities, we get a lot of vulnerabilities. Here am attaching the report html(inside the zip file). 

Could you please suggest what we need to do(other than suppress those).

compile group: 'net.serenity-bdd', name: 'serenity-core', version: versions.serenity
compile group: 'net.serenity-bdd', name: 'serenity-junit', version: versions.serenity
compile group: 'net.serenity-bdd', name: 'serenity-rest-assured', version: versions.serenity
compile group: 'net.serenity-bdd', name: 'serenity-spring', version: versions.serenity 

version: 2.0.11

Thanks,
Venu

**Comment by wakaleo** [comment]
Since there are no _direct_ vulnerabilities with the Serenity code, only in transitive dependencies, I would suggest getting in touch with the authors of these libraries to address said vulnerabilities. Since Serenity is a testing library, it should never be run in production or as part of an externally exposed system, so this is not a high priority issue for us.

**Comment by wakaleo** [comment]
Closing as not relevant to the Serenity code.
