### ISSUE TITLE
How can we know and iterate through multiple web elements returned by a single web locator ? Should it not be a feature of WebElementFacade ?

### ISSUE THREAD

**Issue by PrasadNutalapati** [serenity-bdd/serenity-core#1596]
Hello !
I have come across a situation, that for a given web locator, I am seeing multiple web elements for example in a list like display. With Serenity When I use WebElementFacade instead of Selenium's driver.getElements(By type), I don't have a means to know whether it returned a single web element or multiple. Right now, since I need only the first element, there is no problem as the method just returns the first one any way. What if I want, the Nth one ? 
There is no way I could use WebElementFacade to know and get the some other element other than the very first one. Or is there one ?
Only way for me is to use in PageObject class `getDriver().getElements(By type)` and iterate through them by index.
Please let me know, what I am thinking is right or wrong.

**Comment by wakaleo** [comment]
Github is for defects rather than questions; please ask questions on https://serenity-bdd.rocket.chat or StackOverflow.

The WebElementFacade class wraps the WebElement class, which represents a single element. If you want to find multiple elements, use one of the findBy() methods (see https://serenity-bdd.github.io/theserenitybook/latest/page-objects.html).
