### ISSUE TITLE
Ensure syntax not reported on passing test

### ISSUE THREAD

**Issue by nbarrett** [serenity-bdd/serenity-core#1750]
Given a test with the new _Ensure_ syntax:

```
        actor.attemptsTo(
            Ensure.that(message).text().isEqualTo("Thank you for telling us about this change."));
```

Then this assertion is not shown in the html report if it passes. 

![image](https://user-images.githubusercontent.com/626941/62129411-92f44580-b2ce-11e9-8ca4-9e094c961166.png)

However if the traditional _should_ syntax is used:

```
        actor.should(
            seeThat(the(message), containsOnlyText("Thank you for telling us about this change.")));
```

Then this reports correctly:

![image](https://user-images.githubusercontent.com/626941/62129344-650f0100-b2ce-11e9-97b8-64c1587d2b30.png)

**Comment by wakaleo** [comment]
I'm not seeing this behaviour; is there a specific case where this happens?

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/55986/62131363-f54f4500-b2d2-11e9-8ea1-f9ef7feba756.png">

**Comment by nbarrett** [comment]
I'll try and reproduce an example project with this

**Comment by nbarrett** [comment]
I've done some further investigation and have discovered that when this property is present, the behaviour in this defect can be reproduced:

```
manual.task.instrumentation = true
```

**Comment by scooti9** [comment]
> I'm not seeing this behaviour; is there a specific case where this happens?
> 
> <img alt="image" width="1109" src="https://user-images.githubusercontent.com/55986/62131363-f54f4500-b2d2-11e9-8ea1-f9ef7feba756.png">

@wakaleo could you tell me how you do it this description when Ensure is induced?

Because when I wrote code like this:
`Ensure.thatTheAnswerTo("save button has correct opacity", SAVE_BUTTON_OPACITY).isEqualTo("0.7")`
In report I see this.
![image](https://user-images.githubusercontent.com/27691057/65962795-bcaa2400-e459-11e9-9894-cb8cdebb8f0a.png)

Why I don't see the description "save button has correct opacity"?

Thanks!
