### ISSUE TITLE
ThucydidesSystemProperty.PROPERTIES with typesafe config

### ISSUE THREAD

**Issue by arustamov** [serenity-bdd/serenity-core#1841]
Hi @wakaleo 
I have _serenity.conf_ with _environments_ defined there. Now I'm planning to split my configuration into several config files to support different target platforms (like for instance _webdriver.driver=provided_ I have for web and _webdriver.driver=appium_ for mobile). So instead of comment/uncomment each time based on the target platform I'm about to execute I'd like to point serenity to the specific config file. My current observation is that _ThucydidesSystemProperty.PROPERTIES_ now only works with raw .properties files and not typesafe .conf. Am I missing something here? If I switch to raw properties looks like I will lose _environments_ support as it looks like only works with typesafe
Please advise
Best,
Anton

**Comment by wakaleo** [comment]
That isn't supported at the moment: it would involve some code changed (in the PropertiesFileLocalPreferences class).

**Comment by asuruceanu** [comment]
@wakaleo 
Recently I've upgraded to serenity.core version = 2.1.5 from 2.0.84. I've noticed that the system property '-Dproperties=src/test/resources/serenity_dev.conf" is not taken in consideration in this method _PropertiesFileLocalPreferences.defaultPropertiesConfFile_. See below the method from different versions:

serenity.core version =2.0.84:
```
	private Optional<File> defaultPropertiesConfFile() {
        List<String> possibleConfigFileNames = Arrays.asList(
                optionalEnvironmentVariable(System.getProperty(PROPERTIES)).orElse("src/test/resources/serenity.conf"),
                "src/main/resources/serenity.conf");

        return possibleConfigFileNames.stream()
                .map(File::new)
                .filter(File::exists)
                .findFirst();
    }
```
serenity.core version =2.1.5 (master as well):
```

	    private Optional<File> defaultPropertiesConfFile() {

        List<String> possibleConfigFileNames = new ArrayList<>();

        environmentVariables.optionalProperty(System.getProperty(PROPERTIES)).ifPresent(
                possibleConfigFileNames::add
        );
        serenityConfFileInASensibleLocation().ifPresent(possibleConfigFileNames::add);

        return possibleConfigFileNames.stream()
                .map(File::new)
                .filter(File::exists)
                .findFirst();
    }
```
Could you please update from **_"environmentVariables.optionalProperty(...)"_** to **_"optionalEnvironmentVariable(...)"_**	? I suppose it was  a typo when it has been refactored :), otherwise there is something behind why it has been implemented such.

***(silly) Workaround ;-)***
_VM options: -Dproperties="serenity.conf" -Dserenity.conf="src/test/resources/serenity_peru.conf"_

**Comment by wakaleo** [comment]
Looks like a typo, could you propose a PR?

**Comment by asuruceanu** [comment]
hi @wakaleo 

Please see PR #2073
