### ISSUE TITLE
Validator having two method with same name cause report issue

### ISSUE THREAD

**Issue by krys86** [serenity-bdd/serenity-core#1864]
Hello,
in our Validator class we have this method with following implementation :
```
@Step("Check status code is '{1}'")
public void checkStatusCode(final Response response, final int statusCode) {...}
```

and we use it to perform a validation in this way : 

```
public void checkStatusCode(final Response response, final Status status) {
    checkStatusCode(response, status.getStatusCode());
}
```

By running the test with the second version different times, we can see the followng format (with description)
```
Check status code is '200' 
```
or the one formatted by Serenity 
```
Check status code: net.serenitybdd.rest.decorators.ResponseDecorated@2685a25, 200
```

The message is coherent : it appears in all test or in none of them.

Thanks in advance.

**Comment by wakaleo** [comment]
You would get the first text when a @Step annotated method is called, and the second when a method without a @Step annotation but in an instrumented class is called

**Comment by matthieu-vergne** [comment]
Maybe we were not clear. The context is:
- we have the int-based method with annotation
- we have the Status-based method without annotation, but which call the int-based one
- in our tests, we use the Status-based method

The expected behavior is either:
- to have the default format because we call the non-annotated method
- to have the int-based format because it is called by the non-annotated one

The observed behavior is to have both of them. By executing all our tests, some times the whole report use the default format, the other times it uses the annotation. We always call the same method, but it randomly choose one format or the other and applies it to all the report.

**Comment by matthieu-vergne** [comment]
Do you need more feedback?

**Comment by wakaleo** [comment]
Normally only @Step-annotated methods appear in the reports. Can you provide a sample project that reproduces this behaviour?

**Comment by wakaleo** [comment]
I was unable to reproduce this - if you can provide a simple project please feel free to reopen.

**Comment by matthieu-vergne** [comment]
Sorry for the delay. Since we went through a simplification of our tests, we didn't have this use case anymore. We will reopen it (or open a new one) with proper minimal code if we face it again. Sorry for the inconvenience.
