### ISSUE TITLE
what is the best way to configure chrome driver in Serenity in my local machine?

### ISSUE THREAD

**Issue by vaseemhussain** [serenity-bdd/serenity-core#1938]
I have tried this below methods but still i am not able to invoke chrome Browser and getting this error every time "java.lang.NullPointerException"

Added webdriver.driver=chrome in serenity.properties file.
Created serenities.conf file and set the path to chromedriver.exe by pasting chromedriver.exe in resource folder.
Added mvn dependency
<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-chrome-driver</artifactId>
<version>2.36.0</version>
</dependency>
 also in Pom.xml but is still giving me error as above.

Can u suggest me the best way.

**Comment by wakaleo** [comment]
See https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html

**Comment by githubshinde** [comment]
hi @wakaleo just wondering if serenity supports a browser setup approach similar to [webdrivermanager ](https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager) dependency to get rid of downloading and pointing driver.exe files for different browsers every time? In a long run project it can be annoying to change the driver executable files as the browser version changes.

**Comment by wakaleo** [comment]
Serenity integrates automatically with WebDriverManager in the latest versions.

**Comment by githubshinde** [comment]
> Serenity integrates automatically with WebDriverManager in the latest versions.

Okay. That's great! I am using Serenity BDD version 2.0.55. Let me try upgrading to the latest version.

**Comment by githubshinde** [comment]
@wakaleo I can see from the documentation link above that serenity solves the issue of not having the need to install web libraries on every machine however, how does it know what browser version I am using on my system in order to download the compatible browser binary? does serenity do this automatically through any dependency? upgrading to latest version does not seems to solve my issue of the need to download the compatible driver library.

**Comment by wakaleo** [comment]
It just delegates to WebDriverManager - take a look at https://github.com/bonigarcia/webdrivermanager. It won't install the browser for you though, only the drivers.

**Comment by gigamac** [comment]
I have issues relating to the latest version of Chrome (89, while Serenity core version supports to 87), how can I configure serenity to pick up a downloaded chrome driver version until an update arrives rather than applying a runtime path to downloaded driver (eg in build.gradle, serenity.conf or pom.xml? i would rather have a coded solution than a command line. Makes it less tardy when choosing different browsers. am runnng with firefox for now...

**Comment by VaishnaviNarayanan-kl** [comment]
Am getting "unexpected command response" error in the serenity framework. As the Serenity upgrades chrome driver automatically, how to resolve this issue? Can anyone help? The control is clicking the link but throws the  "unexpected command response". When searched this issue needs a webdriver upgrade.

**Comment by globalworming** [comment]
if you need a specific webdriver, you can create your own like here https://serenity-bdd.github.io/theserenitybook/latest/advanced-webdriver.html
