### ISSUE TITLE
How to point specific URL from multiple environments when we have more than one application URLs for each environment

### ISSUE THREAD

**Issue by ibrahimkhaleel** [serenity-bdd/serenity-core#2008]
Hi, I am trying to implement environment specific application URLs in my project using the Serenity BDD framework. I have more than one application URLs for each QA, PPROD and UAT environments. During each test execution in a specific environment, we are pretty much going back and forth with all these applications. I have shared below serenity.conf file sample with my application URLs at each environment.

environments {
  qa {
    webdriver.app1.url = "https://www.mycompanyqaapplication1.com/"
    webdriver.app2.url = "https://www.mycompanyqaapplication2.com"
    webdriver.app3.url = "https://www.mycompanyqaapplication3.com"
  }
  pprod {
    webdriver.app1.url = "https://www.mycompanypprodapplication1.com/"
    webdriver.app2.url = "https://www.mycompanypprodapplication2.com"
    webdriver.app3.url = "https://www.mycompanypprodapplication3.com"
  }
  uat {
   webdriver.app1.url = "https://www.mycompanyuatapplication1.com/"
   webdriver.app2.url = "https://www.mycompanyuatapplication2.com"
   webdriver.app3.url = "https://www.mycompanyuatapplication3.com"
  }
}

The solution I am looking for below each requirement:
1. We do not need Default URL at all, please let me know how to disable it

2. How to access any app URL (say app1/2/3 from conf file) when specific environment is already set up.
Example Maven command:
mvn clean verify -Dwebdriver.driver=chrome -Denvironment=pprod -Dcucumber.options=src/test/resources/features/search/search_by_keyword.feature

3. For the above requirement with multiple URLs, I have gone through the link already: https://johnfergusonsmart.com/environment-specific-configuration-in-serenity-bdd/
Could you please explain how serenity is reading the base URL for the given URL and how to override its variable name to my own variable. I am unable to understand how serenity is calling only base URL from a specified environment, and how I can point specific application URLs (like app1/2/3) from the same environment when I need it.

I have proposed Serenity BDD to my organization for Web/API/Database automation. I am a beginner level in automation using Selenium Java and Serenity framework. So please assist me with your clear solution so that the above requirements can be maintained to project-specific needs. Thank you.

**Comment by wakaleo** [comment]
The @DefaultUrl just defines a URL that will be used if no other base urls are defined. If you define a `webdriver.base.url` field in your environment-specific config, this value will override the host part of the @DefaultUrl.

If you want to retrieve arbitrary values and open pages using WebDriver.get(), just use EnvironmentSpecificConfiguration.from(environmentVariables).getProperty("my.url");

**Comment by ibrahimkhaleel** [comment]
Hi,
Does Serenity allow us to undeclare both webdriver.base.url and @DefaulURL as our business process has no default base URL. As I described in my question, I would like to declare my applications in the same format for various applications and launch their corresponding application URLs during test execution. 

I have tried by removing both @DefaultUrl and base URL field, it throws me below exception error:

   java.lang.AssertionError: Undefined default URL for page object PageObject
        at net.serenitybdd.core.pages.PageUrls.verified(PageUrls.java:80)
        at net.serenitybdd.core.pages.PageUrls.getStartingUrl(PageUrls.java:58)
        at net.serenitybdd.core.pages.PageObject.open(PageObject.java:802)
        at net.serenitybdd.core.pages.PageObject.open(PageObject.java:791)
 
And regarding the solution, you have shared to retrieve arbitrary values, But how to correspond to each URL value with its related application page after declaring all application URLs in serenity.conf file

**Comment by wakaleo** [comment]
If you don't need @DefaultUrl just use Action classes or Screenplay Tasks and don't bother with the PageObject class at all.

**Comment by wakaleo** [comment]
If you don't need @DefaultUrl just use Action classes or Screenplay Tasks and don't bother with the PageObject class at all.

**Comment by ibrahimkhaleel** [comment]
Hi, After your earlier comment I am able to research with it and I think I am able to find the solution I am looking for. I am now able to launch all applications without being assigned them to default URLs. 

I have one last question to check - I am currently using Serenity Cucumber 4 repository for my project base. As I mentioned in my question I am going to develop this for my testing with  Web, Database, and APIs. Would you please recommend or suggest if this framework is correct suitable with my toolset? Thank you.

**Comment by ibrahimkhaleel** [comment]
.

**Comment by sayedshabihyder** [comment]
Hi, I am trying to implement environment specific application URLs in my project using the Serenity BDD framework. I have more than one application URLs for each QA, PPROD and UAT environments. During each test execution in a specific environment, we are pretty much going back and forth with all these applications. I have shared below serenity.conf file sample with my application URLs at each environment.

environments {
    localhost {
        webdriver.base.url = "http://localhost:8080/"
    }
    staging {
       au {
        webdriver.base.url = "http://staging.devatlant.com"
       }    
       gb { 
       webdriver.base.url = "http://staging.devatlant.com" } 
}
    prod {
        webdriver.base.url = "http://my.super.production.com"
    }
}

The solution I am looking for below each requirement:

We do not need Default URL at all, please let me know how to disable it

How to access any app URL (say au from conf file) when specific environment is already set up.
Example Maven command:
mvn clean verify -Dwebdriver.driver=chrome -Denvironment=pprod -Dcucumber.options=src/test/resources/features/search/search_by_keyword.feature

For the above requirement with multiple URLs, I have gone through the link already: https://johnfergusonsmart.com/environment-specific-configuration-in-serenity-bdd/
Could you please explain how serenity is reading the base URL for the given URL and how to override its variable name to my own variable. I am unable to understand how serenity is calling only base URL from a specified environment, and how I can point specific application URLs (like app1/2/3) from the same environment when I need it.

I have proposed Serenity BDD to my organization for Web/API/Database automation. I am a beginner level in automation using Selenium Java and Serenity framework. So please assist me with your clear solution so that the above requirements can be maintained to project-specific needs. Thank you.

**Comment by globalworming** [comment]
@ibrahimkhaleel 

> I have one last question to check - I am currently using Serenity Cucumber 4 repository for my project base. As I mentioned in my question I am going to develop this for my testing with Web, Database, and APIs. Would you please recommend or suggest if this framework is correct suitable with my toolset? Thank you.

sure, you should be able to use any interface you want in your steps, so browser, http clients, database drivers... should be fine.

**Comment by globalworming** [comment]
@sayedshabihyder  as john said, if you don't need `DefaultUrl` just don't use it, but use Actions or Tasks for that.  For getting the urls, declare `EnvironmentVariables env;` in your test. The [example](https://serenity-bdd.github.io/theserenitybook/latest/environment-specific-config.html#_configuring_different_parameters_for_different_environments) shown in the docs looks pretty straight forward
