### ISSUE TITLE
WebElementFacadeImpl.clear method does not work properly

### ISSUE THREAD

**Issue by martinsefcik** [serenity-bdd/serenity-core#2038]
There were some changes made recently in clear method in #1788, but I guess it still does not work as expected, because when the test is running locally e.g. under Mac but against Selenium Grid hub or against Browserstack and target OS is different e.g. Windows then incorrect shortcut is used for selecting all text and the result of clear method is that key 'a' is entered into text field.

So I guess this clear method should not check local OS type but target OS type to distinguish which shortcut combination should be used.

Tested using version 2.2.1

**Comment by wakaleo** [comment]
Could you propose a PR?

**Comment by martinsefcik** [comment]
I can try, but I'm not sure I will be able to do it. I will need some hint at least how to start.
Is the some possibility how to get remote OS type e.g from driver ?

**Comment by wakaleo** [comment]
Yeah, knowing the remote OS in a general case would be very tricky. Maybe find another general way to clear a text field? I suspect the current approach was done because the intuitive approach (eg use clear()m) doesn’t work.

**Comment by martinsefcik** [comment]
proposal 1: 
Ugly but general solution would be to press backspace many times based text length ... not usable for textareas with large texts - can be very slow.

proposal 2:
Another ugly solution would be to always (on all OSes) use both combinations in following order:
1. CMD+a and DELETE
2. CTRL+a and DELETE
must be in this order because CTRL+a does nothing (only moves cursor at the beginning of textarea) on Mac but CMD+a prints `a` on Windows

It would be better to find some nicer solution, but if it is not possible to get easily target OS type then I don't know how to do it.

**Comment by wakaleo** [comment]
Knowing the target OS will depend on the remote server being used, so does not seem possible in a general case. I think ugly solution #2 would be the least worse.

**Comment by arustamov** [comment]
Hi @wakaleo,

Noticed today serenity clear method implementation stopped working for me and my colleagues in Chrome 97+
It produces some special characters entered instead of getting the input element value blank

Had to switch to the following to resolve the issue:
getJavascriptExecutorFacade().executeScript("arguments[0].value = '';", element);

Wonder if you anyone else experienced the same?

<img width="668" alt="Screenshot 2022-02-04 at 20 12 00" src="https://user-images.githubusercontent.com/5088933/152581681-d9bb5266-e152-40bd-bd10-37e7cbe9f802.png">
<img width="326" alt="Screenshot 2022-02-04 at 20 13 14" src="https://user-images.githubusercontent.com/5088933/152581686-82c16bb9-1598-41f2-886f-d481b56031f6.png">
<img width="617" alt="Screenshot 2022-02-04 at 20 14 04" src="https://user-images.githubusercontent.com/5088933/152581690-ccdc0f9e-d59c-42d5-ad80-3c8e39874882.png">
<img width="615" alt="Screenshot 2022-02-04 at 20 14 16" src="https://user-images.githubusercontent.com/5088933/152581693-70b77af6-dde7-4c02-85fa-d6c1d3f5d95a.png">

**Comment by wakaleo** [comment]
I noticed this today too - I'll push a fix in the next release.

**Comment by wakaleo** [comment]
Fixed in 3.2.0
