### ISSUE TITLE
Cannot extend actor with Kotlin

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/serenity-core#2080]
The core issue is, i don't like the `if (actor.abilityTo(...) != null) doStuff() else doStuffDifferently()` construct. So i hoped by extending the actor, i could use something like 
```
when(actor) { 
  is WebBrowsingActor -> doStuff()
  is ApiUsingActor -> doStuffDifferently()
}
```
basically using marker interfaces instead of abilities to decide what step implementation to use. Using Kotlin i cant extend the actor though.. 
![image](https://user-images.githubusercontent.com/2108984/81786081-8197c500-94ff-11ea-82ee-8b5405201e0f.png)
Accidental override: The following declarations have the same JVM signature...
see https://stackoverflow.com/a/51950911/1359903

do you now of a workaround? would it be possible to change the `Actor` so it can be extended in Kotlin? or do you know of a better way to switch step implementation based on what abilities the actor has?

**Comment by wakaleo** [comment]
Hmmm, one of the points of the Screenplay pattern is to use composition over inheritance so that you don't have to ever extend the Actor class. I like the idea of dynamically switching task implementations based on the available abilities, though.

**Comment by globalworming** [comment]
i might play around with the actor source and performables.. maybe i find a neat way
or do you have an idea on top of your head how this could look like?

**Comment by ricardorlg-aval** [comment]
I have in the past a need like that, the most simple solution that I use was make a code like this:
```kotlin
fun Actor.role():ActorRole=if(abilityTo(UseAMobileDevice::class.java)!=null){
    ActorRole.MobileActor
}else{
    ActorRole.ApiActor
}
sealed class ActorRole{
    object MobileActor:ActorRole()
    object ApiActor:ActorRole()
}
```
And with that I can make something like:
```Kotlin
when (actor.role()) {
    is ActorRole.MobileActor -> actor.attemptsTo(MobileTask)
    is ActorRole.ApiActor -> actor.attemptsTo(ApiTask)
```

**Comment by globalworming** [comment]
Nice, a little bit unDRY but does what it's supposed to do, thanks

**Comment by globalworming** [comment]
> i might play around with the actor source and performables..

i guess will not do anything then and go with the example :)

**Comment by globalworming** [comment]
@ricardorlg-aval what do you think doing this with a performable? #2086

**Comment by wakaleo** [comment]
@jan-molak do you want to chip in?

**Comment by jan-molak** [comment]
@wakaleo - sure :-) OK, so may I present a different line of reasoning?

In the Screenplay Pattern, we have [five building blocks](https://serenity-js.org/handbook/thinking-in-serenity-js/screenplay-pattern.html):
- Actors - who represent the users and external systems interacting with our system
- Abilities - which are thin wrappers around the client libraries the actors need to interact with a given external interface of the system
- Interactions - which represent the most basic activities an actor can perform using the said interface
- Tasks - which aggregate interactions and give them business meaning 
- Questions - which provide the actor with a way to retrieve information about the current state of the system.

There is a concept of a _role_ here too, but it operates at a [higher level of abstraction](https://serenity-js.org/handbook/thinking-in-serenity-js/screenplay-pattern.html#actors) than abilities and interactions. Just like the other five elements of the pattern, the term "role" comes from the system metaphor of a stage performance. It should be interpreted as the role a given actor plays in the performance, the role they play in the system - "a doctor", "a trader", "a writer" are all good examples of actor roles. A "mobile actor" or a "web actor" focus on _how_ the actor can accomplish their task rather than _who_ the actor is and _what_ their responsibilities are. For this reason they're too low-level and I wouldn't recommend using the presence or absence of an ability as a driver to perform one or the other interaction flow.

What I would suggest is to think about the role as an aggregation of abilities, tasks, interactions and questions a given actor has at their disposal.

For example, an actor performing the role of a "Support Engineer" might have an ability to `BrowseTheWeb`, `CallAnApi`, `ManageAServer` and so on. They might also be able to perform a task to `RebootTheServer`. Now, whether or not they should `RebootTheServerViaWebUI`, `RebootTheServerUsingAPICall`, or `RebootTheServerViaSSH` depends on the scenario they're performing, and _not_ on the abilities they have. A "support engineer" will always have all three abilities since it's not like you could suddenly forget how to SSH to a box when you're given a Web UI ;-)

OK, but how would you now vary the screenplay of an actor depending on external factors, like the presence of an env variable, a cucumber tag, etc.?

The approach I take here is to use interaction to [`Check`](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-screenplay/src/main/java/net/serenitybdd/screenplay/conditions/Check.java) (also [available in Serenity/JS](https://serenity-js.org/modules/assertions/class/src/Check.ts~Check.html)) and modelling the task as follows:

- `RebootTheServer` - a high-level task that `Check`s the condition and delegates to an interface-specific task
  - `RebootTheServerViaWebUI` - a web-based implementation of the task
  - `RebootTheServerUsingAPICall` - an API-based implementation of the task
  - and so on...

This approach is, in my view, much easier to follow and debug, and results in a much more flexible design since in some scenarios you might use the lower-level tasks like `RebootTheServerViaWebUI` directly.

Hope this helps!

**Comment by globalworming** [comment]
This does not sound like @jan-molak would discourage using abilities to control which implementation to take. Abilities are flexible, can be set based on external config, at runtime, can be extended...
> In the Screenplay Pattern, we have five building blocks:

Interesting, I count 6 ;) there is the SUT.. the SUT is like.. stage props? Or is the SUT the stage?

Imagine if you will the following:
We have a screenplay where an actor is playing the role of a narrator, attempting to `Monologue`. As narrator on a small stage, we need the ability to `Talk` to the audience. Our screenplay performs well :) So well, it gets played on bigger stages. Now we need an actor with the ability to `Shout` or else nobody in the last ranks will hear us. The screenplay is the same but we now need actors with different abilities because our stage is different.

Im my real life use case I want to make sure, the screenplay performs well on different stages and UIs. The same steps should run in my rest api locally as well as against my remote demo react frontend. Not sure how deployment stages and different UIs fit correctly into the screenplay pattern.

**Comment by jan-molak** [comment]
Haha, I'm enjoying your style, @globalworming!

> Interesting, I count 6 ;) there is the SUT.. the SUT is like.. stage props? Or is the SUT the stage?

SUT is the thing actors interact with, so most likely stage props ;-)

> We have a screenplay where an actor is playing the role of a narrator, attempting to Monologue. As narrator on a small stage, we need the ability to Talk to the audience. Our screenplay performs well :) So well, it gets played on bigger stages. Now we need an actor with the ability to Shout or else nobody in the last ranks will hear us. The screenplay is the same but we now need actors with different abilities because our stage is different.

I love the analogy! I see your point; you could also look at it as an ability to `CommunicateVerbally` and interactions to `Speak` and to `Shout`. In this case, you'd have:

```
Monologue                             // high-level task
  Check whether the stage is large
    and if so: Shout                  // low-level interactions
    otherwise: Speak                  // low-level interactions
```

The reason why I like to model it this way is that I can have the `Check` at various levels of abstraction and the abilities can be kept really simple and oblivious of the context they're being used in.

> Im my real life use case I want to make sure, the screenplay performs well on different stages and UIs. The same steps should run in my rest api locally as well as against my remote demo react frontend. Not sure how deployment stages and different UIs fit correctly into the screenplay pattern.

Thanks for the example. I can certainly see the case for different implementations of the same ability, in which case an actor would work like a dependency injection container where your interaction asks for the ability to `BrowseTheWeb` and it might get a specific implementation like `BrowseTheWebWithWebdriver`, `BrowseTheWebWithCypress`, etc. I think that could be useful.

The value of doing this across abilities is not as clear to me yet, so maybe we could go through a more concrete example?

Let's say entering credit card details.

You could do this via UI:

```
ProvideCreditCardDetailsViaUI
- ProvideCardNumber
  - Enter.theValue('4111').into(...)
  - Enter.theValue('1234').into(...)
  - Enter.theValue('5678').into(...)
  - Enter.theValue('9012').into(...)
- ProvideExpiryDate
  - Enter month
  - Enter year
- ProvideCVV
  - Enter.theValue('123').into(...)
- Submit
  - Click.on(/* submit button */)
```

or by issuing an API call
```
ProvideCreditCardDetailsViaAPI
- Send a POST request with { cardNumber: '4111123456789012', etc }
- Ensure you got 200 back
```

Those two tasks achieve the same objective but are quite different both in terms of complexity and structure.

If I needed the actor to make a decision on which one to use I'd introduce a higher-level task `ProvideCreditCardDetails` that then used a `Check` to delegate to either one of the above.

How would you approach it?

**Comment by globalworming** [comment]
That's basically what I wanted to achieve, having high level tasks and then deciding how to do them based on `Check`s. You could check abilities, or note/remember something or check environment variables . `An "ability" is one of the five building blocks of the Screenplay Pattern. It's what enables the actor to interact with the system under test.` Based on this, abilities sound like the wrong way to achieve that. 

I think i need to rework #2086 and don't do a switch based on abilities but use `Check`. It is more flexible that way. Thanks a lot for you input @jan-molak
