### ISSUE TITLE
@After annotation StageDirector causes NoStageException to be thrown

### ISSUE THREAD

**Issue by jvsanten** [serenity-bdd/serenity-core#2206]
Found with:
- serenity-core 2.2.12 
- serenity-screenplay-2.2.5
- serenity-cucumber5 2.2.5

Possibly partly an IntelliJ-Cucumber-Plugin issue (not seeing the problem while running with Maven - but does occur in IntelliJ when using net.serenitybdd.cucumber.cli.Main as a main class).

The @After annotation above the 'endTheAct()' method in StageDirector gets triggered once a Scenario finishes. This calls OnStage.drawTheCurtain(). drawTheCurtain() calls stage() and does a null check. But as of serenity-screenplay 2.2.1 stage() no longer returns null but throws a NoStageException instead.

This results in every scenario that does not set the stage ending with a NoStageException when run through the IntelliJ Cucumber plugin.

The obvious solution would seem to be either the 'stage()' method in OnStage returning null again rather than throwing the exception, or a different handling of the null check in drawTheCurtain().

Alternatively might be some fix in whatever difference between @RunWith(CucumberWithSerenity.class) and using net.serenitybdd.cucumber.cli.Main causes it not to be thrown when running the TestSuite with Maven. Though the null check drawTheCurtain would still be superfluous as the method it calls seems incapable of returning 'null'.

**Comment by VladmirVolgen** [comment]
It has been a while since this was posted but I think I might be able to help other people with the same issue. 

Could be that you had multiple package definitions in your glue? When you run your tests using net.serenitybdd.cucumber.cli.Main you need to be sure to define your glue with the path to your steps definitions package. That did the trick for me.

![image](https://user-images.githubusercontent.com/35852638/97432715-4bff6080-1914-11eb-9427-bb7ac0ce5c0f.png)
