### ISSUE TITLE
How to configure browserstack launches

### ISSUE THREAD

**Issue by dbogatko** [serenity-bdd/serenity-core#2223]
In the source code of the core library, I see that part for BrowserStack is commented on. Is it ok?
Should I use DEFAULT type and just pass capabilities?

https://github.com/serenity-bdd/serenity-core/blob/3a3d6d47e4410183e786d094e0f9bd80d35f2e2d/serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/RemoteDriverProvider.java#L63

**Comment by thePantz** [comment]
Hello,

see [this documentation](https://serenity-bdd.github.io/theserenitybook/latest/remote.html#_running_serenity_tests_on_browserstack) if you haven't already

Note that if you're trying to run on a mobile device you will need to use an appium driver and configure the following in serenity.conf/serenity.properties

appium.platformName = Android
appium.platformVersion = "10.0"
appium.browserName = Chrome
webdriver.remote.url = "http://<bstackUser>:<bstackKey>@hub-cloud.browserstack.com/wd/hub"

I find this to be a bit strange since all of these details can be configured in the browserstack config.

**Comment by dbogatko** [comment]
@thePantz , thank you. it works.
