### ISSUE TITLE
i want to wait till all the values in my dropdown are loaded, how can i achieve it in serenity?

### ISSUE THREAD

**Issue by globalworming** [serenity-bdd/serenity-core#2293]
i want to wait till all the values in my dropdown are loaded, how can i achieve it in serenity?
can anyone suggest me plz..

_Originally posted by @sudhir-kunchakuri in https://github.com/serenity-bdd/serenity-core/issues/541#issuecomment-722938836_

**Comment by globalworming** [comment]
that depends @sudhir-kunchakuri 

how do you know that the dropdowns are fully loaded?

**Comment by sudhir-kunchakuri** [comment]
that is what my question how can we make sure that all my values in drop down are loaded so that i can proceed further...
in my scenario: the moment i select value in dropdown certain validation will get fire on the screen, different values in drop down have different validation rules..
so thats the reason i want how can we implement that all my values in dropdown are loaded and ready to select..
please suggest..

**Comment by globalworming** [comment]
you either have to point us to an example or tell us what "fully loaded" actually means. are there loading icons? css changes? transitin css classes? do you always know the expected number of values?

**Comment by sudhir-kunchakuri** [comment]
example: i have customer group type dropdown which has fixed three values in it and every group type value have different set of rules or validations ... now i want the system to wait till all my 3 values are completely present in dropdown then i can make any selection so that respective validations will get fire on screen based on selected group type value... 
![Uploading image.png…]()

**Comment by globalworming** [comment]
wait until the number of options is 3. would that help?

**Comment by globalworming** [comment]
Thing is, you need to be able to describe what "completely present" means. How can you see they are present? what differentiates it from "not present"? is there some kind of special class name that's only present on "completely present" entries? 

Or would it be enough to e.g. check the options length before making a change and then wait till option lengths differs?
