### ISSUE TITLE
Error base url not found

### ISSUE THREAD

**Issue by richardmaster** [serenity-bdd/serenity-core#2361]
Hello

I am trying out serenity have spent a lot of time writing my own frameworks,
I  used this in properties file see below but it does not  pick the url when I run open()
and error appears   Undefined default URL for page object PageObject

serenity.project.name=test
webdriver.driver=chrome
webdriver.base.url=https://opensource-demo.orangehrmlive.com
#webdriver.driver=firefox
webdriver.chrome.driver=src/test/resources/drivers/chromedriver.exe
#webdriver.gecko.driver=src/test/resources/drivers/windows/geckodriver.exe
webdriver.timeouts.implicitlywait =10000

@RunWith(SerenityRunner.class) 
public class LogInTest extends PageObject {
	
	
	@Managed(driver="chrome")                                                       
    WebDriver driver;
	
	@Steps
	Homepage home;
	
	@Title("Executing Logging in Test")
	@Test
	public void Logging()
	{
		//driver.get("https://opensource-demo.orangehrmlive.com/");
		System.out.println();
		open();
		home.VerifyTitle();
		home.LogIn();
		home.VerifyDashboard();
	}
	
	

}

**Comment by wakaleo** [comment]
A test case is not a page object, so it shouldn't extend PageObject. Have a look at https://serenity-bdd.github.io/theserenitybook/latest/web-testing-in-serenity.html.

**Comment by richardmaster** [comment]
Hi

that makes perfect sense but if I get rid of it how to I get the open() method or read the properties file ?

**Comment by oleg-rd** [comment]
Hey @richardmaster, you have to call `open()` method of the object of particular page - so in your case it should be smth like `homePage.open()`. It is possible to add annotation `@DefaultUrl ` to the class that represents this page object, however, according to docs, it will be replaced anyway with _webdriver.base.url_ property.

You can read more about these things [here](https://serenity-bdd.github.io/theserenitybook/latest/page-objects.html#_opening_the_page)

Also, just as note - you've annotated your `homePage` field with `@Steps` - it also doesn't look correct, because steps != page objects.

**Comment by Carfixing** [comment]
_hi what is the meaning of property not found error in serenity framework_
