### ISSUE TITLE
Serenity gradle plugin 3.4.1: Aggregate task sometimes fail. 

### ISSUE THREAD

**Issue by MartinxCieslar** [serenity-bdd/serenity-core#2968]
Hi, 
when we run `aggregate` task, sometimes it fails with error (around 70 % of runs)
Tests run in docker with java 11.0.3-jre-slim
gradle wrapper version 7.5.1
net.serenity-bdd.serenity-gradle-plugin:3.4.1
serenity version 3.4.0
 - net.serenity-bdd:serenity-core
 - net.serenity-bdd:serenity-cucumber
 - net.serenity-bdd:serenity-ensure
 - net.serenity-bdd:serenity-rest-assured
 
The `aggregate` task fails with part of stack trace:
```
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate. 
net.serenitybdd.reports.model.DurationDistribution.findMatchingBucketForTestCase(DurationDistribution.kt:208)
net.serenitybdd.reports.model.DurationDistribution.populateDurationBuckets(DurationDistribution.kt:63)
net.serenitybdd.reports.model.DurationDistribution.<init>(DurationDistribution.kt:26)
net.thucydides.core.reports.html.HtmlAggregateStoryReporter.enhanceWithDurationTags(HtmlAggregateStoryReporter.java:271)
net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsIn(HtmlAggregateStoryReporter.java:150)
net.thucydides.core.reports.html.HtmlAggregateStoryReporter.generateReportsForTestResultsFrom(HtmlAggregateStoryReporter.java:134)
 net.thucydides.core.reports.UserStoryTestReporter$generateReportsForTestResultsFrom.call(Unknown Source)
```
Location of the method call in your repo:
https://github.com/serenity-bdd/serenity-core/blob/8b772b3c98982705b2b974d37f75ddbd42df07f1/serenity-stats/src/main/kotlin/net/serenitybdd/reports/model/DurationDistribution.kt#L177

**Comment by wakaleo** [comment]
Sound's tricky to troubleshoot. Can you provide a sample project that reproduces the issue consistently?

**Comment by MartinxCieslar** [comment]
Hi, when I upgraded the serenity plugin to 3.4.2 I was not able to reproduce it. So it seems like it is fixed in that version.

**Comment by baskarcsb** [comment]
Yes even i am facing this issue with 3.4.1

**Comment by wakaleo** [comment]
> Yes even i am facing this issue with 3.4.1
> 
> --- serenity-maven-plugin:3.4.1:aggregate (serenity-reports) @ cpolbdd --- [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time: 34:35 min [INFO] Finished at: 2022-11-23T10:29:15Z [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.4.1:aggregate (serenity-reports) on project cpolbdd: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.4.1:aggregate failed: Collection contains no element matching the predicate. -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

As the previous comment suggests, maybe try with 3.4.2

**Comment by baskarcsb** [comment]
sure john...i will check and update you

**Comment by martin-cieslar-telia** [comment]
Last time I was in a hurry and the same failure occurred soon also on 3.4.2. as mentioned here https://github.com/serenity-bdd/serenity-core/issues/2973

Sorry, I don't have time to investigate it more right now.

**Comment by baskarcsb** [comment]
It failed in even 3.4.2 version

**Comment by wakaleo** [comment]
> It failed in even 3.4.2 version

Thanks for verifying. Can you provide a project that reproduces the issue?

**Comment by Cvarshney-clgx** [comment]
> > It failed in even 3.4.2 version
> 
> Thanks for verifying. Can you provide a project that reproduces the issue?

It may be json file related issue, as I could see it is throwing null when generating json file

**Comment by baskarcsb** [comment]
Hi John,

Tested version: Serenity 3.4.1 

Finally, i am able to replicate the issue ..... and it looks like if any one of the test scenario ran for longer duration (example 10 minutes or greater than 10 minutes) , then the issue is occurring.

Here is the steps To reproduce this issue:

Create one sample script to just launch any web application:

The below code launches the url and wait for 10 minutes on the same session.

	public void openPage() throws Exception {
		open();
		getDriver().navigate().refresh();
		//Assume that the test is running for 10 minutes on a particular session
		//Added thread.sleep for 10 minutes to be on same session or you can pick a test that executes more than 10 minutes. 
		Thread.sleep(600000);
	}

After the test complete the above steps... serenity is trying to aggreagate and generate the report and the final results is.

[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.4.2:aggregate (serenity-reports) on project samplebdd: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.4.2:aggregate failed: Collection contains no element matching the predicate.

if the above error message appears then serenity failed to generate the aggreate report.

Temporary Solution:

as a workaround. I have tested with 3.4.2 with a minor modifcation on the pom by adding the below serenity maven version. 

& Now i found that serenity is properly aggregating the report with out any issues.

<serenity.maven.version>3.1.15</serenity.maven.version>

**Comment by wakaleo** [comment]
@baskarcsb mixing versions is not recommended. Can you provide a sample project or a sample set of json results that reproduces the issue?

**Comment by baskarcsb** [comment]
Sorry for the delay in response John, due to company policy I am unable to upload the sample project from my office laptop. so, i have created a project in my personal laptop and upload to the below location.

https://github.com/baskarcsb/Sample3.4.2

I have used the below  tools in my project:

serenity 3.4.2
Junit 4
java 11
maven 3.8.6

To test the project scenario :  just run mvn clean verify

& It will take approximately 10-12 minutes to complete the execution and then you will get the attached error.

Thanks
CSB





I have created a sample project to get the below error
[ERROR] Failed to execute goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.4.2:aggregate (serenity-reports) on project samplebdd: Execution serenity-reports of goal net.serenity-bdd.maven.plugins:serenity-maven-plugin:3.4.2:aggregate failed: Collection contains no element matching the predicate.

**Comment by baskarcsb** [comment]
Hi John, 

FYI- I have tested the new updated version with our code and it looks like the things are working as expected. -(Testing Cont...)

Once Againg Thank you so much for fixing the aggregate issue in 3.4.3 version.

Great work John ...

**Comment by AlexMukhina** [comment]
Hi,
I see that the latest serenity-gradle-plugin version is 3.4.2 and with that version the issue is reproducible "Execution failed for task ':aggregate'. > Collection contains no element matching the predicate".
Is going to be fixed for gradle plugin any time soon?

**Comment by wakaleo** [comment]
> 

When I get round to it.

**Comment by AlexMukhina** [comment]
waiting then, thank you!

**Comment by ashishagrawal28** [comment]
I am also facing same issue with serenity-maven 3.4.2 version. Is 3.4.3 version has fix for this. 
@all - Please confirm.
