### ISSUE TITLE
Not able to Download a file in headless mode

### ISSUE THREAD

**Issue by srikanthimmidi** [serenity-bdd/serenity-core#3059]
Serenity version : 3.4.2
Serenity.conf file

web-chrome{
webdriver {
                    capabilities {
                                          browserName = "chrome"
                                          acceptInsecureCerts = true
                                          strictFileInteractability = true
                                            "goog:chromeOptions" {
                                                                                args = ["no-sandbox","disable-dev-shm-usage","window- 
                                                                                                    size=1920,1080","version","incognito","headless"]
                                                                                prefs: {
                                                                                                download.default_directory= ${user.dir}"\downloads"
                                                                                                }
                                                                                }
                                          }
                    }
}

Working normal in non headless mode .
In headless file not getting downloaded

@wakaleo need your inputs.

Thanks,
Srikanth

**Comment by wakaleo** [comment]
Sounds like a Selenium or Chromedriver question, but in principle headless mode shouldn't have any limitations on downloads. It's not something Serenity manages directly though.

**Comment by AlexRiaboshapka** [comment]
https://github.com/dotnet/aspnetcore/pull/46812
May be related to some changes in the latest chromedriver see the above issue 

Our E2E tests were timing out as of the update to Chrome 110. I tracked this down to a newly-introduced issue whereby it no longer works if you use --headless and --user-data-dir at the same time. Which some (but not all) of our tests do.

The underlying reason seems to be that Chromium now has two "headless" modes:

The existing, traditional headless mode (--headless). This used to work with --user-data-dir, but as of Chrome 110, that combination stops the browser from even starting up. I doubt that's an intentional regression on the part of Chromium/chromedriver, but nonetheless that's now what happens (also on Chrome and chromedriver v111).
A new headless mode (--headless=new) which seemingly works in all cases including with --user-data-dir. So, this PR switches us over to that mode.
Even if Chrome later fixes --headless, it's still a good thing for us to switch to the newer mechanism, presuming it will remain in support for longer.

**Comment by srikanthimmidi** [comment]
Thanks @AlexRiaboshapka  for your inputs, 

I updated my config my file with --headless=new on Friday it's working now.
Thanks for your support.

I just want to know is there any way to mention download path which works for any OS.
prefs: {
download.default_directory= ${user.dir}"\downloads"}

Currently it works for linux , if want for windows i need to replace \ with // . can we overcome this?

Thanks,
Srikanth

**Comment by AlexRiaboshapka** [comment]
> Thanks @AlexRiaboshapka for your inputs,
> 
> I updated my config my file with --headless=new on Friday it's working now. Thanks for your support.
> 
> I just want to know is there any way to mention download path which works for any OS. prefs: { download.default_directory= ${user.dir}"\downloads"}
> 
> Currently it works for linux , if want for windows i need to replace \ with // . can we overcome this?
> 
> Thanks, Srikanth

Not sure but you can create two different environments in the config: see the example [here](https://github.com/serenity-bdd/serenity-core/issues/1849) 
Or 
You can try using some of the proposed solutions [here](https://stackoverflow.com/questions/36663023/java-file-path-windows-linux) 
`You can use slash character as file separator for both OS, in other words you can use C:/PDFMalwareDataAnalyser/Txt/ instead of C:\\PDFMalwareDataAnalyser\\Txt\\ it will still work on Windows OS.`

**Comment by Tamas-Demeny** [comment]
Need a bit of help, if this is my config file, and works ok, except for the download part. How do I update to new headless mode? Thank you in addvance!

webdriver {
    driver= chrome
    autodownload = true
}

headless.mode = true
chrome.switches="""--disable-dev-shm-usage;--no-sandbox;--disable-download-notification;--test-type;--ignore-certificate-errors;
                   --disable-popup-blocking;--disable-default-apps;--disable-extensions-file-access-check;--start-maximized;
                   --incognito;--disable-infobars,--disable-gpu"""

drivers {
  windows {
    webdriver.chrome.driver = "src/test/resources/webdriver/windows/chromedriver.exe"
    webdriver.gecko.driver = "src/test/resources/webdriver/windows/geckodriver.exe"
    webdriver.ie.driver = "src/test/resources/webdriver/windows/IEDriverServer.exe"
  }
}
