### ISSUE TITLE
Question: How to run with custom web driver

### ISSUE THREAD

**Issue by rjrussell77** [serenity-bdd/serenity-core#345]
I am using Serenity 1.1.28/Java/JUnit and Sauce Labs.  I want to be able to test on mobile platforms like iPad and Android.  I've read many things but cannot find the right combo of properties, either saucelabs or serenity.  The Sauce Labs tech support did some digging and their conclusion was that Serenity does not properly propagate Sauce Labs properties though I cannot 100% confirm it.

Ultimately, I'd like to handle two cases:
a) allow the user to indicate a mobile platform (e.g. "iPad Retina")
b) allow the user to start a test suite without indicating any os/browser/version and let the test suite programmatically decide what to run.
It seems to me that in at least one scenario, I need to completely define the DesiredCapabilities instance myself but I'm not sure when/where to interject this logic given Serenity hard-wiring of objects like Pages and the WebDriver instance.

Please help!
Thanks

**Comment by rajesht81** [comment]
Can you check if the below options works for you?

-Dwebdriver.driver=remote 
-Dserenity.driver.capabilities="browserName:iphone;deviceName:iPad Air;version:9.2"

**Comment by rrussell39** [comment]
@rajesht81 Thanks!  That did it.  This needs to be documented somewhere prominently.  Maybe it is and I missed it.  Can you perhaps point me to the docs, if any, that helped you figure that out?

So now on to part b - how can I build the capabilities on the fly instead of passing on the command line?  Maybe I can simply set the same properties that are passed on the command line at startup time.  I will try this.

**Comment by rrussell39** [comment]
@wakaleo @YamStranger  I am not able to set serenity.driver.capabilities from within the code.  Do you know if it's possible to configure the remote web driver for any device, platform, browser, os, version etc...on the fly - meaning, let the report suite logic determine which platform to run instead of rely on command line params?

**Comment by rajesht81** [comment]
@rrussell39 I didn't find any documentation on Serenity website about this. Found it the hard way by trial and error and debugging (with my limited dev skills)

@wakaleo , @YamStranger  , Would you be able to document this?

**Comment by YamStranger** [comment]
Hello @rrussell39, @rajesht81, thanks for this issue and help as well. 

> I am not able to set serenity.driver.capabilities from within the code. Do you know if it's possible to configure the remote web driver for any device, platform, browser, os, version etc...on the fly - meaning, let the report suite logic determine which platform to run instead of rely on command line params?

If you mean that serenity will run all your tests using all available Sauce Labs webdrivers - no it is not possible. You should specify what particular browser should be used for test. 

About logic to configure remote web driver on the fly - now driver will be initialized if @Managed annotation provided for some WebDriver variable before test method started, using configuration of Souce Labs as well. It seems that there is not possibility to change driver configuration during test execution.... 

So I see next options: 
1. Manage webdriver with your own code, without using serenity
2. Mark this issue as enhancement and try to found out how such behaving can be supported. 
 
____________________

@rajesht81:
>Would you be able to document this?

sure, thanks

**Comment by rrussell39** [comment]
@YamStranger Thanks for taking a look.  This is very helpful.  Regarding your question: 

"If you mean that serenity will run all your tests using all available Sauce Labs webdrivers - no it is not possible. You should specify what particular browser should be used for test. "

No - I don't want to run my tests on ALL available web drivers, I just want to be able to define ONE driver by the code itself and not have to define the driver on the command line or properties.  It would be great to not have the requirement of apriori driver knowledge before Serenity starts up.  If the @Managed annotation is the entity that forces this logic, then I will investigate not using it to see if I can 'manage' it myself.  
The motivation here is to 'randomize' the driver so that you perhaps end up with testing configurations that are weighted towards your particular user base (e.g. 60% of our users use Chrome on Mac, 30% use ipads, 20% windows, etc...)

**Comment by YamStranger** [comment]
@rrussell39 
So, you desire to find some new features in Serenity BDD: 

now it is possible to define driver type using @Managed
```
@Managed(driver="chrome")
```
and you wish some other capabilities (that can be defined test by test), like:
```
@Managed(driver="chrome",
                    webdriver.driver=remote,
                   serenity.driver.capabilities="browserName:iphone;deviceName:iPad Retina;version:9.2")
```
or some source of webdriver properties: 
```
@Managed(propertyProvider = new MyCustomPropertyProvider("chrome"))
```

If so - its looks quite interesting, so it should be implemented

**Comment by arcarchit** [comment]
Hi @rrussell39 : Were you able to find any work around for the issue?

**Comment by rodrigojmartin** [comment]
Interested in this as well!
