### ISSUE TITLE
REST report improvements

### ISSUE THREAD

**Issue by dsmt** [serenity-bdd/serenity-core#384]
First of all, I would like to thank for great improvements in REST reports. 

I would also like to put forward some improvements for the report:

1. Do not print `Content Type` in the beginning of the report because it is already printed in `Header` section;
2. Do not print `Response Cookies` section as it is the copy of `Response Headers` (which already include cookies);
3. Make report more straightforward rearranging following sections from the most to the least important:

- Response Headers
- Response Body
- Request Headers
- Request Body

![](http://take.ms/QIEgT)

Thanks

**Comment by YamStranger** [comment]
@dsmt Thanks for this idea. 
Reports are updated: if response cookies are the same as request - they will not be included in report, changed sequence based on your recommendation, but request and after that response data. 

Content type will be keep in headers as well as in bottom of this page, because it should not contains charset (and in content-type header all be included)

![responce_headers_body_cookies](https://cloud.githubusercontent.com/assets/1667699/15053229/43bf421a-130a-11e6-9973-b8ae4b3e7238.png)
![request_headers_body](https://cloud.githubusercontent.com/assets/1667699/15053230/43c41c4a-130a-11e6-932f-ec8b3c15c396.png)

Thanks!!!
