### ISSUE TITLE
Gradle and Maven integration behave differently 

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#464]
I've discovered some issues with the latest rc of Serenity. I'm using a sample project (https://github.com/hypery2k/serenity_sample) and the generated reports are differenty for [Gradle ](https://martinreinhardt-online.de/jenkins/view/Demos/job/serenity_gradle_sample/Serenity_Report/)and [Maven](https://martinreinhardt-online.de/jenkins/view/Demos/job/serenity_maven_sample/Serenity_Report/).

Any ideas why?

**Comment by wakaleo** [comment]
Could you elaborate on the differences you are seeing?

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better

http://johnfergusonsmart.com  | reachme@johnfergusonsmart.com
<john.smart@wakaleo.com>___________________________________________________


On 28 June 2016 at 1:41:06 PM, Martin Reinhardt (notifications@github.com)
wrote:

I've discovered some issues with the latest rc of Serenity. I'm using a
sample project (https://github.com/hypery2k/serenity_sample) and the
generated reports are differenty for Gradle
<https://martinreinhardt-online.de/jenkins/view/Demos/job/serenity_gradle_sample/Serenity_Report/>
and Maven
<https://martinreinhardt-online.de/jenkins/view/Demos/job/serenity_maven_sample/Serenity_Report/>
.

Any ideas why?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/serenity-bdd/serenity-core/issues/464>, or mute the
thread
<https://github.com/notifications/unsubscribe/AADasqTE0UKbz7i1SRnHFOjg8A6iRN-tks5qQRZhgaJpZM4JADnT>
.

**Comment by hypery2k** [comment]
The number of testcases and failed tests differ:
Gradle:
![gradle](https://cloud.githubusercontent.com/assets/979121/16415967/42ce9b2a-3d40-11e6-8110-6dabde817c33.jpg)
Maven:
![maven](https://cloud.githubusercontent.com/assets/979121/16415970/4616cf28-3d40-11e6-8805-f97c5490d209.jpg)

**Comment by YamStranger** [comment]
@hypery2k Thanks for this issue. 

It seems that maven report somehow doesn't contains full examples from parameterized test. Basically I see that Searching by keyword should display the corresponding article fails,  and some test with name Legacy test dissipated. 

It seems that reason is parallel executing (in maven you use 2 parallel forks and in gradle 8).

Will investigate this. 

Thanks!

**Comment by wakaleo** [comment]
This appears to work in 1.7.0
