### ISSUE TITLE
Ignored tests are marked as Skipped

### ISSUE THREAD

**Issue by g-dimartino** [serenity-bdd/serenity-core#763]
I'm using a '_CucumberWithSerenity_' runner and scenarios marked with @ignore are not marked as ignored, in the serenity report, but as skipped; moreover, those scenarios are actually executed.

To make the cucumber runner ignore those scenarios I have added a @Before hook that throws a '_AssumptionViolatedException_' and, in this way, the scenario is not executed and properly marked as ignored in the serenity report. But if I annotate the hook to catch only the scenarios annotated as @ignore, the serenity report marks all the steps as ignored (and they are actually not executed) but the scenario as skipped.

This is my hook:
	@Before ("@Ignore, @Ignored, @ignore, @ignored")

	public static void ignoredTest () {
		throw new AssumptionViolatedException("This test has been ignored");
	}

And this is the result:
![schermata 2017-04-14 alle 16 10 32](https://cloud.githubusercontent.com/assets/27094466/25045498/f6b83c38-212c-11e7-88be-721bd516eddd.png)

**Comment by wakaleo** [comment]
"Ignored" and "Skipped" are currently treated as synonyms in Serenity Cucumber.

When Serenity ignores a test, it still steps through the methods, but WebDriver calls are deactivated. You can also check this manually (for example, if you want to skip test data injection in a @Before method) by calling `StepEventBus.getEventBus().currentTestIsSuspended()`.

The @Given,@When, @Then etc methods will always be executed. This is how Serenity reports on the test structure even for pending and ignored tests. It is recommended practice for Cucumber step definitions to contain no implementation code, and delegate to @Step methods or ScreenPlay performables to do the actual work. 

If you want the @Step methods to be entirely skipped, you can use ` @Step(callNestedMethods = false)`. In this case, nested steps will not appear in the reports.

You can choose to not run the tests entirely using Cucumber tags, but in this case they will not appear at all in the test reports.

**Comment by g-dimartino** [comment]
Ignored and Skipped are two different things for serenity.

If I throw a '_AssumptionViolatedException_', the @Given,@When, @Then etc methods are not executed; and if I create a hook for a different tag (not @ignore, @ignored, @wip, @skip, @manual) the scenario is marked as ignored, while if I use those tag the scenario is marked as skipped.

If you want I can send you my project again.

**Comment by wakaleo** [comment]
Agreed; the ignored/skipped reporting in Cucumber will be fixed in version 1.1.29.

**Comment by g-dimartino** [comment]
Thank you!

Anything I can do in the meanwhile? For example to override the calculated result in a @After hook.

**Comment by Hendrione** [comment]
Dx○•○°•••\•☆•wZAdeeAxaAadXEEexar@●•\~'r


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: g-dimartino <notifications@github.com> Date: 4/15/17  10:18 PM  (GMT+07:00) To: serenity-bdd/serenity-core <serenity-corexEeaxadXsadaaAesXxJSaX@noreply.github.com>!@@÷!'#•▪~•÷EaCc: Subscribed <subscribed@noreply.github.com> Subject: Re: [serenity-bdd/serenity-core] Ignored tests are marked as Skipped (#763) 
Ignored and Skipped are two different things for serenity.
If I throw a 'AssumptionViolatedException', the @Given,@When, @Then etc methods are not executed; and if I create a hook for a different tag (not @ignore, @ignored, @wip, @skip, @manual) the scenario is marked as ignored, while if I use those tag the scenario is marked as skipped.
If you want I can send you my project again.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/serenity-bdd/serenity-core","title":"serenity-bdd/serenity-core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/serenity-bdd/serenity-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@g-dimartino in #763: Ignored and Skipped are two different things for serenity.\r\n\r\nIf I throw a '_AssumptionViolatedException_', the @Given,@When, @Then etc methods are not executed; and if I create a hook for a different tag (not @ignore, @ignored, @wip, @skip, @manual) the scenario is marked as ignored, while if I use those tag the scenario is marked as skipped.\r\n\r\nIf you want I can send you my project again.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/serenity-bdd/serenity-core/issues/763#issuecomment-294299541"}}}
