### ISSUE TITLE
SerenityRunner alternative

### ISSUE THREAD

**Issue by jizel** [serenity-bdd/serenity-core#779]
Hi, I'm leaving Cucumber (with Serenity) and switching to JUnit tests with EasyTest (https://github.com/EaseTech/easytest). It seems to be much better option for REST API data driven testing. However I'd like to keep Serenity as a (great) reporting tool for my tests.

The problem is I need to use EasyTest's DataDrivenTestRunner to run my tests so I cannot use SerenityRunner (and of course I cannot implement a new Runner extending both because multiple inheritance in Java is a no no).

So, I have a very ugly (but working) solution. I've simply copied the contents of DataDrivenTestRunner to my new Runner and set it to extend SerenityRunner instead of BlockJUnit4ClassRunner.

For obvious reasons I don't want to keep this as a final solution. Is there any way to do this nicely? Probably using Rules? 
I only need the report-generating functionality, I'm not using @Steps annotation to autowire classes. Does anyone see a good solution that is not incredibly painful to implement?

Thanks for your tips.

**Comment by wakaleo** [comment]
JUnit is a horrible code base to work with for this sort of thing. Unfortunately JUnit Rules do not have all the features of a JUnit runner (otherwise Serenity would have switched to Rules a long time ago). The simplest (more elegant) solution would be to port the EasyTest features into Serenity, possibly with some reuse of the easytest-core classes.
