### ISSUE TITLE
Serenity runner ingest exception

### ISSUE THREAD

**Issue by DmitriyMa** [serenity-bdd/serenity-core#837]
@Step
	public String createNewFolder(String CollaboratorId) {
              .....
              String CollaboratorId = `"123456789";`
              page.response.waitForCondition().until(ExpectedConditions.textToBePresentInElement(el, message));
		return CollaboratorId;
        }
This method thews an error (it can be catched by surrounding with try+catch block). But in fact, method will return null.

Expected:
Exception was thrown and test failed.

<serenity.version>1.5.0-rc.1</serenity.version>

**Comment by wakaleo** [comment]
This is because you are annotating the createNewFolder() method with the @Step annotation. When a web interaction fails, the test will continue in "dry-run" mode so as to document all the steps in the test. Normally, @Step-annotated methods are not designed to return methods - they model actions, not queries. So in dry-run mode, there will be nothing to return after a WebDriver interaction has failed ( which is why it is returning null).

In the next version of Serenity (1.5.0-rc.2), methods that return strings, numbers and booleans will return "", 0, or false respectively.
