### ISSUE TITLE
Test Name is not sent to Browserstack

### ISSUE THREAD

**Issue by bebef1987** [serenity-bdd/serenity-core#872]
After #846 was fixed we go a new commit that breaks this feature.

From a regression range it looks like a45d498c50581f11038ab64236b4338df09a5216 broke the browser stack name.

When we get  Thread.currentThread().getStackTrace() at [line](https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/webdriver/capabilities/RemoteTestName.java#L13) we don't get the test name anymore

Here is a compare of these stacktraces:
![image](https://user-images.githubusercontent.com/703611/28922957-d76aa566-7864-11e7-8232-46517287ba97.png)

@cliviu you worked on this. Do you know if there is a way to avoid this?

@wakaleo @cliviu Is there some other way to get the test name at this stage?

**Comment by bebef1987** [comment]
from more debugging I found out that the driver is initiated at https://github.com/serenity-bdd/serenity-core/commit/a45d498c50581f11038ab64236b4338df09a5216#diff-656842476439ba60ff42fea4807ae7dcR39 and not when we call the Open method as it used to.

Is this the desired flow?

**Comment by wakaleo** [comment]
No, that looks wrong. Calling ` ((WebDriverFacade) driver).getProxiedDriver()` instantiates the driver, which should only be done the first time the browser is used (so in the Open method previously). Rather than checking the getProxiedDriver() class, this method should use the WebElementFacade's driverClass field. This will need a change to the WebElementFacade class to avoid calling the getProxiedDriver() method unnecessarily.

**Comment by bebef1987** [comment]
@wakaleo this is a little bit out of my skill zone :D Do you or @cliviu have time to fix this please?

**Comment by bebef1987** [comment]
Fixed in 4e4cd0a Hopefully a release will be out soon.
